is_debug = false
is_official_build = false
is_component_build = false
skia_enable_ganesh = true
skia_enable_graphite = true
skia_use_gl = true
skia_use_vulkan = true
skia_use_metal = false
skia_use_direct3d = false
skia_use_dawn = false
skia_enable_pdf = false
skia_enable_skottie = true
skia_enable_svg = true
skia_use_libjpeg_turbo_decode = true
skia_use_libjpeg_turbo_encode = true
skia_use_libwebp_decode = true
skia_use_libwebp_encode = true
skia_use_libavif = false
skia_use_libjxl_decode = false
skia_use_wuffs = true
skia_use_expat = true
skia_use_dng_sdk = false
skia_use_piex = false
skia_use_harfbuzz = true
skia_use_icu = true
skia_use_system_harfbuzz = false
skia_use_system_icu = false
skia_enable_skshaper = true
skia_enable_skunicode = true
skia_enable_skparagraph = true
